Rewriting backend and possibly frontend
KiwiTalk/KiwiTalk pull request #1171
Opened 2022-08-31 11:31 UTC by storycraft

Requirements
* [x] Integrate every rust crates need into one workspace.
* [ ] Rewrite backend to Rust
* [ ] Ports frontend

This pr close #833

2022-08-31 11:37 UTC, storycraft commented
바뀐 것들
1. 지원중단된 node-kakao 사용을 중단하고 Rust 구현체를 도입합니다.
2. nw.js를 tauri로 교체합니다.
3. 키위톡 조직 내 각각의 저장소에 있던 Rust 라이브러리들을 모두 키위톡 crates 폴더 워크스페이스로 이동했습니다.
4. package.json, Cargo.toml내 코드 작성자 목록을 `KiwiTalk Contributors`로 통합했습니다.

2022-09-01 02:11 UTC, RanolP requested changes
코멘트로 단 제안 사항도, 달지 않은 제안 사항도 함께 정리하자면

1. 일부 파일에서 포매팅이 제대로 되지 않은 것 같습니다. (파일 끝 줄바꿈 규칙 등)
2. `readme.md`로 이름지어진 파일이 보이는데 특별한 이유가 없다면 `README.md`로 이름 규칙을 통일하는 건 어떨까요?
3. 에러 구현 보면 `From`, `Display`, `Error`가 손수 구현되어 있는데, `thiserror`를 써서 `#[derive(Error)]`하는 건 어떨까요?
4. `Cow<'a, str>`를 단순히 읽기만 하는 경우 `&'a str`로 교체가 가능해보입니다.
5. `'static` 수명이 몇 있는데, 잘못 사용하고 있을 확률이 높아보입니다.
6. 이 PR이 너무 크기 때문에 프론트엔드 등의 나눌 수 있는 PR의 경우 별개 PR을 통해 재점검하는 편이 좋겠습니다.

2022-09-01 02:11 UTC, RanolP commented on frontend/public/index.html
> +<!doctype HTML>
기존 index.html 내용을 옮겨오지 않으신 이유가 있으신가요? 새로운 시작도 나쁘지는 않은데 이건 다른 분들 의견도 들어보면 좋겠네요.

2022-09-01 02:11 UTC, RanolP commented on LICENSE
> -                                 Apache License
라이선스 파일을 지우신 이유가 있으신가요?

2022-09-01 02:11 UTC, RanolP commented on crates/kiwi-talk-app/tauri.conf.json
> +{
번들 정보가 미비한데, 현재 PR에서 완결지을지, 별개 PR에서 완수하도록 둘지 결정하시면 될 것 같습니다.

2022-09-01 02:11 UTC, RanolP commented on crates/talk-api-client/src/auth/mod.rs
> +    pub config: AuthClientConfig<'static>,
`'static` 수명 쓰는 거면 뭔가 잘못된 것 같습니다. `AuthClientConfig` 내부가 모든 수명을 `'static`으로 써도 문제가 없거나, `TalkAuthClient`에 수명 `'a`를 추가하는 게 맞을 것 같습니다.

2022-09-01 02:18 UTC, RanolP commented
제가 알기론 DeepScan이 TypeScript 관련 코드만 검사할텐데, 저기서 나온 이슈는 전부 무시하고 프론트엔드 고치는 PR에서 따로 고치는 게 좋겠습니다.

2022-09-01 03:31 UTC, storycraft commented on LICENSE
> -                                 Apache License
라이선스가 이미 Cargo.toml과 package.json에 정의되어 있고, 일부 에셋들은 다른 라이선스를 사용할 수 도 있기 때문에 저장소 최상위에 있던 라이선스 파일은 지웠습니다.

2022-09-01 03:35 UTC, storycraft commented on crates/kiwi-talk-app/tauri.conf.json
> +{
아직 완벽하게 정해지지 않은 부분은 기본값으로 두었습니다. 별개 PR에서 완수하는게 좋을거 같습니다.

2022-09-01 03:43 UTC, storycraft commented on crates/talk-loco-command/src/command/mod.rs
> +    pub method: Cow<'static, str>,
해당 부분은 상수와 `String` 값을 둘다 받을 수 있도록 의도적으로 이렇게 작성했습니다

2022-09-01 03:44 UTC, storycraft commented on crates/talk-api-client/src/auth/mod.rs
> +    pub config: AuthClientConfig<'static>,
`TalkAuthClient`에 수명 `'a`를 추가하는것이 좋을 것 같습니다

2022-09-01 03:47 UTC, storycraft commented on frontend/public/index.html
> +<!doctype HTML>
새로운 시작을 위해 새로 만들었습니다만 기존 index.html의 내용을 옮겨오는게 더 좋을것 같네요

2022-09-01 04:32 UTC, RanolP commented on crates/talk-loco-command/src/command/mod.rs
> +    pub method: Cow<'static, str>,
아 'static 관련해선 제가 잘못 알았네요

2022-09-01 04:46 UTC, RanolP commented on LICENSE
> -                                 Apache License
패키지 정보에 라이선스가 정의되어 있음과 별개로 그게 언제부터 적용되는지, 누가 소유주인지, 그 조항이 어떻게 되는지 등을 읽어볼 수 있는 "문서"로써의 라이선스 파일은 필요하다고 생각합니다. 단순 MIT라는 문자열론 어떤 권한과 제약이 주어지는지 알기 어려우니까요. 다른 라이선스를 사용하는 경우는 README.md에서 안내하면 되지 않을까요?

2022-09-01 04:52 UTC, storycraft commented on LICENSE
> -                                 Apache License
문서로서 라이센스 파일은 필요할 것 같네요. 이 부분은 다시 추가하겠습니다.

2022-09-01 11:23 UTC, storycraft commented on crates/talk-api-client/src/agent.rs
> +pub enum TalkApiAgent<'a> {
해당 불필요한 `Cow<'a, str>`은 제거 했습니다

2022-09-01 11:23 UTC, storycraft commented on crates/talk-api-client/src/auth/xvc/default.rs
> +    first: Cow<'a, str>,
해당 불필요한 `Cow<'a, str>`은 제거 했습니다

2022-09-01 11:41 UTC, RanolP commented
수고하셨습니다!

2022-09-01 11:57 UTC, RanolP approved these changes

2022-09-01 14:05 UTC, merged