키위톡 로코 클라이언트 구현
KiwiTalk/KiwiTalk pull request #1267
Opened 2022-10-08 12:45 UTC by storycraft

키위톡 로코 클라이언트의 기본 기능을 구현합니다.

## 변경사항
추가 예정

이 PR은 #1254 가 완료되기 전까지 merge 할 수 없습니다.

2023-02-06 06:17 UTC, RanolP requested changes
- RowIndex를 &str 대신 숫자를 쓰는 이유는 뭔가요? 가능하면 가독성이 높은 &str 쪽으로 통일하면 좋겠습니다.
- DB 스키마를 문서화할 필요가 있습니다. ORM을 사용하지 않으므로 코드에서 DB 스키마를 추측하려면 꽤나 많은 양을 읽어야 합니다. (추가 PR 권장) : 후속 이슈 #1484 
- crate 간의 구조, 서버 - 클라이언트 소통 구조 등의 아키텍처적인 부분을 문서화할 필요가 있습니다. (추가 PR 권장) : 후속 이슈 #1485 
- 문자열에 SQL을 쓰는 결정을 내렸으므로 sql 변경 시 validity 검증을 위한 리뷰 프로세스나 도구 등을 구비해야 합니다. (팀 내 문화 설정, 추가 PR 가능성 있음) : 후속 이슈 #1486 
- > The error message given by the Display representation of an error type should be lowercase without trailing punctuation, and typically concise.
    
    https://rust-lang.github.io/api-guidelines/interoperability.html?highlight=message#error-types-are-meaningful-and-well-behaved-c-good-err
    위 규칙에 따라, 에러 메시지는 소문자로 시작하는 편이 좋습니다.

2023-02-06 06:17 UTC, RanolP commented on crates/talk-loco-command/src/response/mod.rs
> +    pub fn get<T: DeserializeOwned>(self) -> Result<T, bson::de::Error> {
get보다는 try_deserialize 같은 명시적인 이름을 쓰는 건 어떨까요?

2023-02-06 06:17 UTC, RanolP commented on crates/talk-loco-command/src/response/mod.rs
> +    pub data: Document,
data가 pub일 필요가 있나요? pub fn get()을 통해 deserialize해서 접근하는 것 외에 사용처가 있는지 궁금해요.

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct LoggedChat {
이름이 LoggedChat인데에는 이유가 있나요? Chatlog와 LoggedChat이 무슨 차이인지 궁금하고, 차이가 없다면 use talk_loco_command::structs::chat::Chatlog as LocoChatlog와 같이 쓰는 것도 나쁘지 않을 것 같아요.

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct ChatType;
enum repr를 사용하지 않는 데에는 이유가 있나요? Other 같은 걸 표현할 수단이 필요한감

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct Chat {
추측컨대, 구조체가 담는 내용이 Chat(대화방)보다는 Message(메시지)에 가까운 것 같아보여요

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/channel/user.rs
> +pub struct DisplayUser {
DisplayUser는 뭘 담는 타입인가요? :eyes:

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/config.rs
> +    pub fn create_client_info(&self) -> ClientInfo {
as_loco() 같은 함수명은 어떨까요?

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/database/pool.rs
> +    pub fn spawn_task<R: Send + 'static, F: FnOnce(PooledConnection) -> PoolTaskResult<R>>(
이 함수가 async fn이 아닌 이유는 뭔가요?

2023-02-06 06:17 UTC, RanolP commented on crates/talk-loco-client/src/lib.rs
> +    tasks: (JoinHandle<()>, JoinHandle<()>),
read_task, write_task로 나누지 않고 tasks로 묶어서 들고 있는 이유가 뭔가요?

2023-02-06 06:17 UTC, RanolP commented on crates/talk-loco-client/src/lib.rs
> +fn session_task() -> (ReadTask, WriteTask) {
다른 곳에 재활용될 여지가 없는 인라인 함수 같은데, LocoRequestSession::new에 합쳐버려도 되지 않을까요?

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/event/channel.rs
> +pub struct ReceivedChat {
얘는 왜 아래의 구조체랑 달리 (동)+(명)으로 이름지었나요?

2023-02-06 06:17 UTC, RanolP commented on crates/kiwi-talk-client/src/channel/mod.rs
> +impl From<ChannelInfo> for ChannelData {
ChannelInfo와 ChannelData는 뭐가 다른가요? 둘 다 Info/Data가 잡음인 것 같아보입니다.

2023-02-09 17:23 UTC, storycraft commented on crates/kiwi-talk-client/src/channel/user.rs
> +pub struct DisplayUser {
DisplayUser는 일반 채팅방의 미리보기 아이콘을 만드는데 사용됩니다. 원래 오픈채팅방에서도 사용되었는데 특정 업데이트 이후로는 사용하지 않는것 같습니다

2023-02-09 17:25 UTC, storycraft commented on crates/kiwi-talk-client/src/database/pool.rs
> +    pub fn spawn_task<R: Send + 'static, F: FnOnce(PooledConnection) -> PoolTaskResult<R>>(
&self의 lifetime 문제때문에 그랬던걸로 기억합니다.

2023-02-09 17:27 UTC, storycraft commented on crates/talk-loco-client/src/lib.rs
> +    tasks: (JoinHandle<()>, JoinHandle<()>),
처음에 task를 딱히 구분할 필요가 없어서 그렇게 해놨는데 이제 분리하는게 낫겠네요

2023-02-09 17:29 UTC, storycraft commented on crates/talk-loco-client/src/lib.rs
> +fn session_task() -> (ReadTask, WriteTask) {
이 부분도 원래 다른 작업도 있는 긴 함수여서 분리한건데 합쳐도 좋을것 같습니다

2023-02-09 17:32 UTC, storycraft commented on crates/talk-loco-command/src/response/mod.rs
> +    pub data: Document,
status키를 포함하는 응답 데이터를 표현하는건데 pub가 아닐 이유가 없지 않나요?

2023-02-09 17:33 UTC, storycraft commented on crates/talk-loco-command/src/response/mod.rs
> +    pub fn get<T: DeserializeOwned>(self) -> Result<T, bson::de::Error> {
try_deserialize를 쓰는게 좋을 것 같네요

2023-02-09 17:36 UTC, RanolP commented on crates/kiwi-talk-client/src/channel/user.rs
> +pub struct DisplayUser {
1. 대화방의 미리보기 아이콘을 만드는 데에 사용하는 거라면 "사용자"로 복구할 필요가 없을 것 같은데, `impl From<DisplayUserProfile> for UserProfile`이 구현된 이유가 궁금해요. 만약 복구할 필요가 없다면 지워도 좋을 것 같아요.
1. DisplayUser라는 이름이 구조체의 역할(일단, 사용자User로 기능할 필요가 없다는 점에서 미스매치)을 잘 전달하지는 못하는 것 같은데, 당장 생각나는 더 좋은 이름은 없으니 추후 문서화를 통해 역할을 설명하는 방향으로 개선하도록 해요.

1번은 이 PR에서 이야기해보면 좋겠고, 2번은 이 PR에서 문서를 개선하셔도 좋고, 나중에 몰아서 (...) 하셔도 좋습니다.

2023-02-09 17:44 UTC, RanolP commented on crates/kiwi-talk-client/src/database/pool.rs
> +    pub fn spawn_task<R: Send + 'static, F: FnOnce(PooledConnection) -> PoolTaskResult<R>>(
논리적으로는 self.clone()을 하니까 self에 엮이는 라이프타임 오류는 없을 것 같고, 아래와 같이 코드를 고쳐도 `cargo check`에서 컴파일 오류는 없어서 괜찮은 것 같아요! 혹시 동작상 달라지는 부분이 생기나요? 더 나아가 clone 없이 self.get()을 호출해도 컴파일 오류는 발생하지 않는 걸 확인했어요. 'static 라이프타임 제약 조건도 제거할 수 있어보여요. 제가 실행해보지는 않아서 동작이 같은지 검증해주시고, 개선할 수 있는 부분만 반영해주시면 될 것 같아요!

```rs
pub async fn spawn_task<R: Send + 'static, F: FnOnce(PooledConnection) -> PoolTaskResult<R>>(
    &self,
    closure: F,
) -> PoolTaskResult<R>
where
    F: Send + 'static,
{
    let this = self.clone();
    let connection = this.get()?;

    closure(connection)
}
```

2023-02-09 17:50 UTC, RanolP commented on crates/talk-loco-command/src/response/mod.rs
> +    pub data: Document,
대체로 get()을 통해 deserialize된 패킷 정보를 읽는 걸 기대하는 코드를 짤 것 같아서 data에 직접 접근할 필요가 없어보여 드린 말이었어요! data에 대해서는 pub을 제거해도 현재 코드베이스 전체가 정상적으로 컴파일되는 걸 확인했어요.

2023-02-09 17:52 UTC, storycraft commented on crates/kiwi-talk-client/src/channel/mod.rs
> +impl From<ChannelInfo> for ChannelData {
ChannelInfo는 CHATINFO 응답 패킷에 있는 chatInfo 객체의 난독화를 제거해 접근할 수 있게 하기 위한 것 이고 ChannelData는 키위톡 클라이언트에서 사용할 공통 채팅방 정보를 담아놓은 구조체입니다. ChannelData 구조체에 있는 정보가 더 적습니다. ChannelInfo의 경우 단순히 난독화 제거가 목적이기 때문에 채팅방 타입에 따라 존재할수도, 존재하지 않을 수도 있는 데이터들의 경우 전부 Option으로 처리되어 있습니다.

2023-02-09 17:59 UTC, RanolP commented on crates/kiwi-talk-client/src/channel/mod.rs
> +impl From<ChannelInfo> for ChannelData {
패킷 이름이 CHATINFO라 ChannelInfo에 Info가 붙었군요.. 이해했습니다. 다만 ChannelData에서 Data는 붙이지 않아도 될 것 같은데, 혹시 Channel의 Data만 담는 ChannelData와 실제 동작(뮤트 등)까지 수행할 수 있는 Channel이 나뉘게 될 예정인가요? 그렇지 않다면 Data는 네이밍에서 군더더기일 것 같아요.

2023-02-09 17:59 UTC, storycraft commented on crates/kiwi-talk-client/src/channel/user.rs
> +pub struct DisplayUser {
1의 경우 db 유저 정보 업데이트용으로 사용될 수 있어서 구현해놓은걸로 기억하는데 정확히 기억이 안나네요.

실제 서버에서 정보를 줄때는 아이콘에 사용되는 4명이 아니라 거의 모든 유저들을 다 주기 때문에 실제로 제대로 전달하지 못하는건 맞는데 이부분은 제가 어떻게 되어있는지 정확히 모르기 때문에 일단 그냥 두도록 하겠습니다.

2023-02-09 18:02 UTC, RanolP commented on crates/kiwi-talk-client/src/channel/user.rs
> +pub struct DisplayUser {
어려운 문제네요. 그렇다면
- 이러한 사정을 이 PR에서 바로 문서화하실 예정이라면 문서화하신 후 이 이슈를 resolve해주시고,
- 추가 PR로 만드실 예정이라면 바로 resolve하시고, 이슈 트래커든 개인 투두리스트든 어딘가에 기록해두신 다음, 추후 작업하시면 될 것 같습니다.

2023-02-09 18:07 UTC, storycraft commented on crates/kiwi-talk-client/src/database/pool.rs
> +    pub fn spawn_task<R: Send + 'static, F: FnOnce(PooledConnection) -> PoolTaskResult<R>>(
spawn_task 메서드가 존재 하는 이유가 sqlite 관련 호출이 전부 blocking이기 때문에 tokio::task::spawn_blocking을 내부적으로 사용하면서 데이터베이스 작업을 좀 더 편하게 하기 위함이라 저렇게 바꾸기는 어려울것 같네요. 그리고 위에 말했던 lifetime문제는 tokio::spawn과 같이 사용했을때 발생했던걸로 기억합니다.

2023-02-09 18:12 UTC, storycraft commented on crates/kiwi-talk-client/src/channel/mod.rs
> +impl From<ChannelInfo> for ChannelData {
Data를 붙인이유라면 해당 구조체는 채팅방 id를 갖고 있지 않고 Data를 땔경우 다른 비슷한 이름들을 가진 구조체와 헷갈릴것 같아서 어쩔수 없이 붙인 부분이 있습니다.

> 혹시 Channel의 Data만 담는 ChannelData와 실제 동작(뮤트 등)까지 수행할 수 있는 Channel이 나뉘게 될 예정인가요

실제 동작을 수행하는 ClientChannel이 따로 있습니다.

2023-02-09 18:24 UTC, storycraft commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct ChatType;
enum repr사용하면 as 써서 변환하는게 불편하더라고요. 상수 값들 모아놓는 열거형으로는 러스트에서는 enum보단 이런식으로 쓰는게 개인적으로 좀 더 나은 것 같습니다.

추가로 삭제된 메세지의 경우 타입에 16384 or된 값으로 옵니다.

2023-02-09 18:25 UTC, storycraft commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct LoggedChat {
차이라면 위 ChannelData, ChannelInfo와 같습니다만 이 부분의 경우 차이나는 부분이 없고 앞으로도 없을것 같기 때문에 같이 쓰는게 좋을 것 같네요

2023-02-09 18:31 UTC, storycraft commented on crates/kiwi-talk-client/src/event/channel.rs
> +pub struct ReceivedChat {
별 다른 생각없이 봤는데 별로네요. 아래 구조체와 동일하게 바꿨습니다.

2023-02-09 18:40 UTC, storycraft commented
에러 메세지의 경우 af5aab8955814ed8429e0b4fac6af2bbe62cd9eb 에서 전부 소문자로 시작하도록 고쳤습니다.

RowIndex의 경우 from_row가 구조체와 정확히 한 형식의 쿼리에만 대응되고 숫자를 사용하는게 더 빠르기 때문에 &str를 사용하는 의미가 크게 없는것 같아 바꾼건데 다시 &str을 사용하는게 좋을까요?

2023-02-10 04:51 UTC, RanolP commented
DB 스키마가 잘 문서화된다면 어느쪽을 택하든 괜찮습니다만 스키마가 문서로 없는 상황에선 컬럼 이름과 인덱스 사이 대응 관계가 코드만으론 바로 파악되지 않다보니 제안드린 사항이었어요. 저희가 prepared statement 등에서 WHERE로 필터링하거나, select로 선택할 떄에는 이름을 사용하게 될 가능성이 높고, 숫자와 이름이 번잡하게 공존하는 것보다는 이름만으로 통일하는 편이 좋을 것 같아요.

2023-02-10 04:54 UTC, RanolP commented on crates/kiwi-talk-client/src/channel/mod.rs
> +impl From<ChannelInfo> for ChannelData {
관계가 좀 복잡미묘하긴 한데... 여기서 리팩터할 사항은 아닌 것 같으니 일단 resolve해두고, 추후 관계의 문서화, 혹은 재구조화가 필요할 수는 있겠어요.

2023-02-10 04:59 UTC, RanolP commented on crates/kiwi-talk-client/src/database/pool.rs
> +    pub fn spawn_task<R: Send + 'static, F: FnOnce(PooledConnection) -> PoolTaskResult<R>>(
아... 얘가 blocking하는구나.. 이해했어요. 제가 코드를 잘못 읽었네요. resolve하겠습니다.

2023-02-10 05:02 UTC, RanolP commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct ChatType;
비트 플래그면 좀 미묘하긴 하네요. 그래도 단순히 정수로 다루는 것보다는 newtype pattern을 써서 ChatType(i32)로 저장하면 좋을 것 같아요. 실수로 i32 연산하는 걸 막고, 만약 필요한 경우(말씀하신 16384를 or한 경우를 검증하는 등)에는 적절한 이름을 부여하도록 하게끔.

2023-02-10 10:54 UTC, storycraft commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct Chat {
채팅이라는 의미에서 Chat을 사용했습니다. log id(서버쪽 챗 id)와 이전 채팅의 log id를 갖고 있는 구조체 이름이 Chatlog인데 이건 패킷에 있는걸 그대로 따른 거에요. 패킷쪽에서는 채팅방과 채팅(메세지)를 전부 chat하나로 표시해서 (가끔 채팅방의 경우 chatRoom으로 쓴 경우도 있음) 제가 NodeKakao때부터 이부분은 구분하기 쉽도록 channel, chat으로 나눠서 썼습니다.

2023-02-10 11:03 UTC, RanolP commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct Chat {
Telegram API도 그렇고 Chat이라는 이름을 대화방을 나타내는 데에 쓰는 경우가 꽤 있다보니 조금 혼동이 있긴 하네요. 개인적으로는 해당 개념을 표현할 때 Message라는 이름을 선호하긴 합니다만, 멘탈 모델이 제대로 잡혀 있어 구분에 문제가 없다면 그냥 문서화에서 그런 점을 언급하며 작성해주시면 될 것 같아요.

2023-02-13 04:15 UTC, storycraft commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct ChatType;
newtype 패턴을 적용하는게 좋을 것 같네요

2023-02-13 15:25 UTC, storycraft commented on crates/kiwi-talk-client/src/chat/mod.rs
> +pub struct ChatType;
적용했습니다 5c0dd693e243ce01115bc6f626fcd8a9ce043ce4

2023-02-13 15:25 UTC, storycraft commented on crates/kiwi-talk-client/src/config.rs
> +    pub fn create_client_info(&self) -> ClientInfo {
일단 구분을 위해서 loco를 붙이긴 하겠습니다.

2023-02-13 18:01 UTC, RanolP approved these changes

2023-02-13 18:04 UTC, merged

2023-02-13 18:19 UTC, RanolP commented
https://github.com/KiwiTalk/KiwiTalk/pull/1267#pullrequestreview-1274239038

앞서 단 리뷰 코멘트의 내용을 이슈로 만들었습니다.

- #1484 
- #1485 
- #1486