feat: configuration
KiwiTalk/KiwiTalk pull request #1904
Opened 2023-09-20 07:30 UTC by Su-Yong

# BE
- `Configuration` 세분화
- `AuthConfiguration` 추가

# FE
- `useConfiguration` hook 추가
- `react` -> `solid` 마이그레이션 이후 signal이 비정상적으로 동작하는 문제 일부 해결

# Note
- rustlang을 잘 못해서 be부분 이상한거 있으면 적극적으로 수정해주시면 감사하겠습니다

2023-09-20 11:59 UTC, storycraft requested changes

2023-09-20 11:59 UTC, storycraft commented on crates/kiwi-talk-app/src/app/configuration/locale.rs
> +use serde::{Serialize, Deserialize};
`Locale`을 따로 서브 모듈로 분리한 이유가 있나요?

2023-09-20 11:59 UTC, storycraft commented on crates/kiwi-talk-app/src/app/configuration/auth.rs
> +    None,
`AuthConfiguration`에 `None`을 추가하지 말고, `Option<AuthConfiguration>`을 사용하는것도 좋을 것 같아요

2023-09-20 11:59 UTC, storycraft commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
createEffect가 필요한 이유가 있나요?

2023-09-20 12:15 UTC, Su-Yong commented on crates/kiwi-talk-app/src/app/configuration/locale.rs
> +use serde::{Serialize, Deserialize};
앞으로 Configuration모듈에 현재 있는 Auth, Locale말고도 theme같은 다른 설정들도 필요하게 될텐데, 그렇게되면 추후에 GlobalConfiguration의 하위 항목중 Locale만 파일이 분리되어 있지않고, GlobalConfiguration이 선언된 모듈에 `Locale`이 있는게 어색해보여서 미리 분리했습니다.

2023-09-20 12:17 UTC, Su-Yong commented on crates/kiwi-talk-app/src/app/configuration/auth.rs
> +    None,
일단 fe 단에서는
```ts
type NoneAuth = { type: 'None' };
type AccountSaveAuth = { type: 'AccountSave'; email: string; };
type AutoLoginAuth = { type: 'AutoLogin'; email: string; token: string; };
```
으로 되어있는데 Option을 사용하게되면 `null | AccountSaveAuth | AutoLoginAuth`로 사용하면 되겠네요
일단 이 방향으로 수정해보겠습니다

2023-09-20 12:40 UTC, Su-Yong commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
제가 지금 고민중인게, 이부분 때문에 리팩토링을 좀 해야할것으로 보입니다
이코드가 생긴 이유는 `react` -> `solid-js`로 마이그레이션하면서 정말 `react`코드 자체를 1대1 대응시켜서 `solid-js`로 바꿨는데,  react랑 solid랑 이런 input 다루는 부분이 달라 생기게 되었습니다.

원래 `react`코드는 defaultValue를 이용하여 초기값을 넣게 되어있었으나, `solid`에서는 defaultValue가 존재하지 않습니다.
따라서 solid에서 초기값을 바꾸기 위해선 무조건 signal을 설정해주어야 하는데, 현재 구조는 `checkbox` 내부의 signal을 조작하여 값을 컨트롤 하기 때문에 외부에서 값이 바뀌면 내부의 signal도 바뀌어야 합니다
그래서 `createEffect`를 넣어 내부 signal도 바뀌게 설정하였습니다.

이것보다 좀더 우아한방법은
https://github.com/organization/alspotron/blob/master/renderer/components/Card.tsx#L8-L30
이런 방법인것 같은데, 링크에 걸린 코드를 보시면 `expand`와 `setExpand`를 signal로 전달하는 경우에 props에서 전달받은 값을 그대로 사용하고, 그렇지 않은 경우에는 시그널을 생성해냅니다 (리액트와는 다르게 solid-js훅은 rules-of-hooks의 영향을 받지 않습니다)
제가 생각하기에는 base component들에게 `value`를 주지 않았을 경우에도 동작할수 있게 하기 위해선 링크에 걸려있는 방식처럼 사용하는게 적절하다고 생각됩니다.

그런데 이렇게 바꾸기 위해선 전체 구조자체를 변경하는게 좋아보입니다 (지금은 중간에 defaultValue를 어디서든 넣을수 있게 state 드릴링된 방식이여서 좀 비효율적으로 보여요) 

그래서 지금 이부분을 `solid`스럽게 리팩토링 할까 discussion이나 이슈를 열려고했는데 먼저 짚어주셨습니다.
`solid`처럼 fe코드를 리팩토링 해야한다면 이부분은 일단 넘어가고, 그렇지 않다면 해당 checkbox부분을 위에 언급한 코드처럼 고치면 될것같네요

결론) 3줄요약
1. 지금 현재 solid-js코드는 react스럽다
2. 그래서 solid-js스럽게 리팩토링을 하는 것이 좋다.
3. 근데 아직 리팩토링 되지 않아서 임시로 `createEffect`를 땜빵한것이다

2023-09-20 12:51 UTC, storycraft commented on crates/kiwi-talk-app/src/app/configuration/locale.rs
> +use serde::{Serialize, Deserialize};
제가 질문을 잘못 했네요. configuration 모듈을 여러개의 서브 모듈로 나눈 이유가 있나요?

2023-09-20 12:55 UTC, Su-Yong commented on crates/kiwi-talk-app/src/app/configuration/locale.rs
> +use serde::{Serialize, Deserialize};
앞답글이랑 같은 맥락이긴한데 요약하면 한파일에 모든 config들이 다 정의되어있으면 너무 파일이 커질거같아서 미리 분리했습니다

2023-09-20 13:15 UTC, storycraft commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
> 원래 `react`코드는 defaultValue를 이용하여 초기값을 넣게 되어있었으나, `solid`에서는 defaultValue가 존재하지 않습니다. 따라서 solid에서 초기값을 바꾸기 위해선 무조건 signal을 설정해주어야 하는데, 현재 구조는 `checkbox` 내부의 signal을 조작하여 값을 컨트롤 하기 때문에 외부에서 값이 바뀌면 내부의 signal도 바뀌어야 합니다 그래서 `createEffect`를 넣어 내부 signal도 바뀌게 설정하였습니다.

원래 `react`코드가 `defaultValue`를 이용하였으면 그걸 그대로 `value`로 바꾸면 `solid`에서 자연스럽게 동일한 동작을 하지 않나요? `CheckBox` 내부 상태는 현재 어떤 아이콘을 표시해야하는지 정하기 위해서 필요한 것이라 prop 에서 주어진 값과 상관없이 실제 DOM의 값과만 일치하면 됩니다.

2023-09-20 13:20 UTC, storycraft commented on crates/kiwi-talk-app/src/app/configuration/locale.rs
> +use serde::{Serialize, Deserialize};
이 부분은 다른분들 의견도 들어봐야 할 것 같습니다. 제 생각으로는 저 파일에는 구조 선언만 들어가기 때문에 문서화가 되어도 파일이 너무 커질 것 같지는 않거든요,

2023-09-20 13:20 UTC, Su-Yong commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
> > 원래 `react`코드는 defaultValue를 이용하여 초기값을 넣게 되어있었으나, `solid`에서는 defaultValue가 존재하지 않습니다. 따라서 solid에서 초기값을 바꾸기 위해선 무조건 signal을 설정해주어야 하는데, 현재 구조는 `checkbox` 내부의 signal을 조작하여 값을 컨트롤 하기 때문에 외부에서 값이 바뀌면 내부의 signal도 바뀌어야 합니다 그래서 `createEffect`를 넣어 내부 signal도 바뀌게 설정하였습니다.
> 
> 원래 `react`코드가 `defaultValue`를 이용하였으면 그걸 그대로 `value`로 바꾸면 `solid`에서 자연스럽게 동일한 동작을 하지 않나요? `CheckBox `내부 상태는 현재 어떤 아이콘을 표시해야하는지 정하기 위해서 필요한 것이라 prop 에서 주어진 값과 상관없이 실제 DOM의 값과만 일치하면 됩니다.

이게 좀 여러가지 얽혀있는데, 저 `checkbox`를 사용하는곳은 `react`의 `useRef`를 이용하여 defaultValue가 들어가게 설정되어있었습니다.

그런데 react의 경우 `useRef`의 값을 `defaultValue`로 지정하게 되면, `useRef`를 사용한 컴포넌트안에 선언된 다른 state가 변경되면 컴포넌트를 새로 랜더링하고, 그과정에서 제일 최신 ref값으로 설정이 됩니다. 하지만 solid의 경우에 동일한 컴포넌트 내에서 선언된 signal이 바뀐다고 해서, 그 컴포넌트가 리렌더링 되는게 아니기때문에, solid의 `useRef`(일반 변수입니다)의 경우에는 값이 바뀌어도 바뀐값이 전달되지 않습니다.

그래서 초기 value를 바꾸기 위해서는 signal을 전달하여야 하고, 따라서 초기 value값이 undefined였다가, 내부 백엔드와 통신하여 새 값을 가져오게 되면 `signal`값이 바뀌고, 이때 `checkbox`입장에서 바뀐 `signal`값은 `checkbox`컴포넌트가 아닌, 외부 `props`에서 전달된 값이기 떄문에 외부에 값에 따라 변경하도록 해야 현재 아이콘이 반영이 됩니다

2023-09-20 13:24 UTC, JellyBrick commented on crates/kiwi-talk-app/src/app/configuration/locale.rs
> +use serde::{Serialize, Deserialize};
저는 추후 확장을 고려할때, 미리 분리하는 것이 맞는 것 같습니다

2023-09-20 13:52 UTC, storycraft commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
useRef가 어떤 부분을 말씀하시는건가요?

2023-09-20 13:56 UTC, Su-Yong commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
https://github.com/KiwiTalk/KiwiTalk/blob/250b8729eff74f88a126ec2672fa1748bbbd4eb7/frontend/src/app/login/content/index.tsx#L46

이부분이 원래 useRef였습니다

2023-09-20 14:24 UTC, storycraft commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
> `CheckBox` 내부 상태는 현재 어떤 아이콘을 표시해야하는지 정하기 위해서 필요한 것이라 prop 에서 주어진 값과 상관없이 실제 DOM의 값과만 일치하면 됩니다.

react 코드에서는 checked, indeterminate 속성 사용시에 그냥 state값을 사용해도 잘 작동해서 그대로 사용했는데, solid로 변환시에는 signal값이 아닌 prop값을 적용하게 바꿔야 의도대로 작동 할 것 같네요.

2023-09-20 14:35 UTC, Su-Yong commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
그럼 그작업을 모든 베이스 컴포넌트에 다해야하는데 이브랜치에서 다할까요 아니면 일단 체크박스만 하고 넘어갈까요?

2023-09-20 14:46 UTC, storycraft commented on frontend/src/components/check-box/index.tsx
> +  createEffect(() => {
일단 체크박스만 해주세요

2023-09-21 02:55 UTC, storycraft approved these changes

2023-09-21 02:56 UTC, merged