로그인 페이지 v2 디자인 적용
KiwiTalk/KiwiTalk pull request #2089
Opened 2023-10-20 05:32 UTC by Su-Yong

## Description
<img width="1283" alt="image" src="https://github.com/KiwiTalk/KiwiTalk/assets/13764936/95f66a70-9767-498f-bd38-3a92c72f0f84">

로그인 페이지에 KiwiTalk v2 디자인을 적용합니다

## Changelog
<img width="1283" alt="image" src="https://github.com/KiwiTalk/KiwiTalk/assets/13764936/f0c729ee-1236-4c4a-a8dc-65757a157bfa">

- [X] LoginListPage
<img width="1283" alt="image" src="https://github.com/KiwiTalk/KiwiTalk/assets/13764936/8f85923b-2823-430a-b862-9c3a89add2bb">

- [X] LoginPage
- [ ] DeviceRegisterPage (WIP)
- [ ] PasscodePage

## Migration
<img width="224" alt="image" src="https://github.com/KiwiTalk/KiwiTalk/assets/13764936/7a886da2-a43b-46f0-ae19-c645d34eac82">

- 자동 로그인 설정 포맷이 변경되었습니다 `%appdata%/org.kiwitalk.kiwitalk/`폴더 하위에 있는 `save_account`를 삭제해주세요
- Windows: `~/%APPDATA%/org.kiwitalk.kiwitalk`
- mac: `~/Library/Application Support/org.kiwitalk.kiwitalk`

2023-10-20 09:33 UTC, storycraft requested changes
1. 프론트엔드 코드가 너무 난잡합니다. 각 부분들은 컴포넌트로 만들어 storybook으로 볼 수 있어야 합니다. 또한 개별 컴포넌트별로 분리될수 있는 로직들은 분리해주세요.
2. `DeviceRegisterPage`와 같이 두개의 페이지가 필요할 경우 개별 컴포넌트들로 분리하고 상위 컴포넌트를 만들어 하나로 묶으세요.
3. `DeviceRegisterPage` 컴포넌트에 초기화되지 않은 변수들이 있습니다. 이 또한 2를 참고하여 고쳐주세요.
4. `Migration` 섹션은 breaking changes에 대한 세부 내용과 간단한 고치는 법을 적는 부분입니다. 특정 부분이 바뀐다고해서 업데이트 했을 때 프로그램이 오작동하면 안됩니다.

2023-10-20 09:41 UTC, Su-Yong commented
> 1. 프론트엔드 코드가 너무 난잡합니다. 각 부분들은 컴포넌트로 만들어 storybook으로 볼 수 있어야 합니다. 또한 개별 컴포넌트별로 분리될수 있는 로직들은 분리해주세요.
> 
> 2. `DeviceRegisterPage`와 같이 두개의 페이지가 필요할 경우 개별 컴포넌트들로 분리하고 상위 컴포넌트를 만들어 하나로 묶으세요.
> 
> 3. `DeviceRegisterPage` 컴포넌트에 초기화되지 않은 변수들이 있습니다. 이 또한 2를 참고하여 고쳐주세요.
> 
> 4. `Migration` 섹션은 breaking changes에 대한 세부 내용과 간단한 고치는 법을 적는 부분입니다. 특정 부분이 바뀐다고해서 업데이트 했을 때 프로그램이 오작동하면 안됩니다.

1. 모든 element를 다 스토리북으로 불러오게해야하나요? 예를들어 LoginPage안에 있는 이메일, 패스워드, 버튼을 담고있는 form같은것도 포함이신건가요?
2. DeviceRegisterPage는 passcode때문에 분리해야한다고 생각하신거같은데, 너무
3. 초기화되지않은변수는 문제가아닙니다 null이나 undefined로 초기화 시키면 1회만 초기화하고 값변경이 없다고 prefer-const 문제가 뜹니다 그렇다면 ref를 callback형태로 쓰게 강제해야할까요?
4. 제가 계속 수정하려했으나, 이전 파일 데이터가 있는경우에 io오류가 계속 발생합니다 제가 migration항목에 저렇세 서술해둔 이유는, 지금은 완전히 개발단계이기때문에 문제없다고 생각했기때문입니다

4번은 제가 어떻게 고치고싶지만 러스트를 많이만져본게아니여서 감이안옵니다 어떻게해야 io문제가 발생하지않을까요?

2023-10-20 10:03 UTC, storycraft commented
> 1. 모든 element를 다 스토리북으로 불러오게해야하나요? 예를들어 LoginPage안에 있는 이메일, 패스워드, 버튼을 담고있는 form같은것도 포함이신건가요?
> 2. DeviceRegisterPage는 passcode때문에 분리해야한다고 생각하신거같은데, 디자인안에서 passcode가 deviceRegister랑 분리되어있지않아서 묶었습니다
> 3. 초기화되지않은변수는 문제가아닙니다 null이나 undefined로 초기화 시키면 1회만 초기화하고 값변경이 없다고 prefer-const 문제가 뜹니다 그렇다면 ref를 callback형태로 쓰게 강제해야할까요?
> 4. 제가 계속 수정하려했으나, 이전 파일 데이터가 있는경우에 io오류가 계속 발생합니다 제가 migration항목에 저렇세 서술해둔 이유는, 지금은 완전히 개발단계이기때문에 문제없다고 생각했기때문입니다
> 
> 4번은 제가 어떻게 고치고싶지만 러스트를 많이만져본게아니여서 감이안옵니다 어떻게해야 io문제가 발생하지않을까요?

1. 네.
2. 디자인안에 passcode 입력 창이 없습니다. 한 페이지에 있어야 되는게 아니라 그냥 디자인이 안되어 있는 겁니다. 그리고 코드 구성은 디자인과는 별개입니다. 코드가 어떻게 되어있든 디자인안하고 보이는것만 같으면 됩니다.
3. 이 부분은 `ref`를 쓸 필요가 없습니다. 다른 방법중 하나로는 `form`을 사용해서 구현하는게 있겠네요.
4. io 오류가 나도 상관없습니다. 사용자 정보 로드시 io 오류는 복구 가능한 오류입니다. 해결 방법으로는 io 오류 발생시 오류 메세지를 표시하고 default 값을 반환하는 방법이 있겠네요.

2023-10-20 10:18 UTC, Su-Yong commented
> 1. 네.
> 2. 디자인안에 passcode 입력 창이 없습니다. 한 페이지에 있어야 되는게 아니라 그냥 디자인이 안되어 있는 겁니다. 그리고 코드 구성은 디자인과는 별개입니다. 코드가 어떻게 되어있든 디자인안하고 보이는것만 같으면 됩니다.
> 3. 이 부분은 `ref`를 쓸 필요가 없습니다. 다른 방법중 하나로는 `form`을 사용해서 구현하는게 있겠네요.
> 4. io 오류가 나도 상관없습니다. 사용자 정보 로드시 io 오류는 복구 가능한 오류입니다. 해결 방법으로는 io 오류 발생시 오류 메세지를 표시하고 default 값을 반환하는 방법이 있겠네요. 이 부분 해결이 어려우시다면 나중에 제가 고치도록 하겠습니다.

1. storybook은 `_component` 단위정도에만 적용되면 된다고 생각합니다. `_component`폴더 안에 빼먹은게 있으면 스토리북을 만드려고 하는데, 제가 위에서 언급한것처럼 "LoginPage안에 있는 이메일, 패스워드, 버튼을 담고있는 form"등은 page안에 바로 구현해도 무방하다고 봅니다. 이런부분은 오히려 스토리북을 만드는게 일을위한 일이 될거라고 생각되네요. 이에대해 어떻게생각하시나요?
2. 알겠습니다 사실 너무 파일이 많아질거같아서 대충 애매하다고 느낀 이부분을 하나로 통합했습니다. 조금이따가 해결하도록 하겠습니다
3. 이부분은 해결했습니다
4. 복구가능한 오류이기때문에 제가 default값으로 넣고 싶었지만, 러스트 코드를 많이 짜본게 아니다보니 잘아시는분이 코드짜는게 훨씬 좋아보여서... 좀 부탁드립니다 ㅎㅎ (그런데 mac에서는 개발도중에 오류가 났었는데 windows에서는 오류가 안나긴했습니다.)

2023-10-20 10:33 UTC, storycraft commented
> 1. storybook은 `_component` 단위정도에만 적용되면 된다고 생각합니다. `_component`폴더 안에 빼먹은게 있으면 스토리북을 만드려고 하는데, 제가 위에서 언급한것처럼 "LoginPage안에 있는 이메일, 패스워드, 버튼을 담고있는 form"등은 page안에 바로 구현해도 무방하다고 봅니다. 이런부분은 오히려 스토리북을 만드는게 일을위한 일이 될거라고 생각되네요. 이에대해 어떻게생각하시나요?
> 2. 알겠습니다 사실 너무 파일이 많아질거같아서 대충 애매하다고 느낀 이부분을 하나로 통합했습니다. 조금이따가 해결하도록 하겠습니다
> 3. 이부분은 해결했습니다
> 4. 복구가능한 오류이기때문에 제가 default값으로 넣고 싶었지만, 러스트 코드를 많이 짜본게 아니다보니 잘아시는분이 코드짜는게 훨씬 좋아보여서... 좀 부탁드립니다 ㅎㅎ (그런데 mac에서는 개발도중에 오류가 났었는데 windows에서는 오류가 안나긴했습니다.)

1. `_component`에 들어가는 컴포넌트들의 기준이 어떻게 되나요?
4. 네.

2023-10-20 11:47 UTC, Su-Yong commented
> 1. `_component`에 들어가는 컴포넌트들의 기준이 어떻게 되나요?
> 
> ...
> 
> 4. 네.

`_component`에 들어가는 기준은 공통적으로 "해당`_component`폴더가 위치한 곳의 도메인에서만 사용되는가" 하나가있고, 두번째 기준은 "해당 도메인에서 재사용되는가?" or "해당 도메인의 `page.tsx` 흐름에 벗어나는 컴포넌트인가?" 입니다.

해당 도메인에서 재사용되는 컴포넌트의 경우 `ChannelItem`, `Profile`, `ErrorTip`과 같은 컴포넌트가 있을것이고,
해당 도메인의 `page.tsx` 흐름에 벗어나는 컴포넌트의 경우에는 `KiwiBackground`, `SideBar`, `ChannelList`등이 있습니다.
제가 여기서 말한 `page.tsx`의 흐름에 벗어난다는 말은 한 페이지가 가지는 컨트롤 플로우에 방해가 되는 코드가 존재하냐라는 말입니다.

예를들어 `KiwiBackground`같은 경우에는 로그인 페이지의 백그라운드 디자인을 담당하는 컴포넌트로, 로그인 페이지의 목적인 "사용자를 KiwiTalk에 로그인 하고 메인페이지로 랜딩시킨다" 라는 목적에 부합하지 않습니다. 따라서 `KiwiBackground`를 별개의 컴포넌트로 분리했습니다. (실제 KiwiBackground.tsx는 별 코드가 없고, 흐름상 크게 문제가 없는것 같지만, KiwiBackground.css.ts에 디자인을 구현하기 위한 많은 코드가 있기때문에 분리하였습니다)

두번째 예시로 `SideBar`의 경우입니다. `SideBar`를 사용하는 `MainPage`의 경우, 사용자가 어떤 페이지를 사용할 것이며, 그 페이지를 컨트롤 하는 목적입니다. 해당 목적으로 봤을때, `SideBar`의 세부 구현은 (config에 따라 notification Icon이 on, off된다던가, collapse된다던가) MainPage가 알 이유가 없으며 따라서 `page.tsx`의 흐름에 벗어나 분리를 하였습니다.

마지막 예시로 `ChannelList`는 `ChannelListPage`에 구현되어있는데, `ChannelListPage`의 목적은 사용자가 어떤 채널을 선택하여 채팅을 시작하고 볼것인지 정해주는 역할로, Channel들을 어떻게 보여줄지 (검색하거나, 어떤 디자인으로 보이거나)는 관심사가 아닙니다. 따라서 `ChannelList`로 분리하였습니다.

이러한 기준으로 _component에 들어갈 컴포넌트들을 분리하고 있습니다. 1번의 이유인 "해당 도메인에서만 재사용됨"은 너무 명확하기 때문에 따로 storybook을 만드는게 맞다고 보지만 위에서 언급한 LoginPage에 LoginInpput, PasswordInput을 담은 form은 그저 UI를 배치하는 방식이며 form안에서 validation을 진행하지 않고, LoginPage의 목적인 "사용자의 이메일, 패스워드를 입력받아 로그인을 진행한다"에 부합하기때문에 굳이 분리시키지 않았습니다.
물론 이러한 기준은 사람들마다 의견이 다를수 있을것같습니다. 그래서 차라리 storybook을 만들어야하는 컴포넌트를 집어주신다면 제가 작업을 할수 있을것 같습니다.

(그리고 이걸 간단하게 요약하면 UI를 구현하는 코드가 많다면(관심사의 분리) `_component`에 구현한다고 생각할수있습니다)

2023-10-20 12:31 UTC, storycraft commented
> `_component`에 들어가는 기준은 공통적으로 "해당`_component`폴더가 위치한 곳의 도메인에서만 사용되는가" 하나가있고, 두번째 기준은 "해당 도메인에서 재사용되는가?" or "해당 도메인의 `page.tsx` 흐름에 벗어나는 컴포넌트인가?" 입니다.
> 
> 해당 도메인에서 재사용되는 컴포넌트의 경우 `ChannelItem`, `Profile`, `ErrorTip`과 같은 컴포넌트가 있을것이고,
> 해당 도메인의 `page.tsx` 흐름에 벗어나는 컴포넌트의 경우에는 `KiwiBackground`, `SideBar`, `ChannelList`등이 있습니다.
> 제가 여기서 말한 `page.tsx`의 흐름에 벗어난다는 말은 한 페이지가 가지는 컨트롤 플로우에 방해가 되는 코드가 존재하냐라는 말입니다.
> 
> 예를들어 `KiwiBackground`같은 경우에는 로그인 페이지의 백그라운드 디자인을 담당하는 컴포넌트로, 로그인 페이지의 목적인 "사용자를 KiwiTalk에 로그인 하고 메인페이지로 랜딩시킨다" 라는 목적에 부합하지 않습니다. 따라서 `KiwiBackground`를 별개의 컴포넌트로 분리했습니다. (실제 KiwiBackground.tsx는 별 코드가 없고, 흐름상 크게 문제가 없는것 같지만, KiwiBackground.css.ts에 디자인을 구현하기 위한 많은 코드가 있기때문에 분리하였습니다)
> 
> 두번째 예시로 `SideBar`의 경우입니다. `SideBar`를 사용하는 `MainPage`의 경우, 사용자가 어떤 페이지를 사용할 것이며, 그 페이지를 컨트롤 하는 목적입니다. 해당 목적으로 봤을때, `SideBar`의 세부 구현은 (config에 따라 notification Icon이 on, off된다던가, collapse된다던가) MainPage가 알 이유가 없으며 따라서 `page.tsx`의 흐름에 벗어나 분리를 하였습니다.
> 
> 마지막 예시로 `ChannelList`는 `ChannelListPage`에 구현되어있는데, `ChannelListPage`의 목적은 사용자가 어떤 채널을 선택하여 채팅을 시작하고 볼것인지 정해주는 역할로, Channel들을 어떻게 보여줄지 (검색하거나, 어떤 디자인으로 보이거나)는 관심사가 아닙니다. 따라서 `ChannelList`로 분리하였습니다.
> 
> 이러한 기준으로 _component에 들어갈 컴포넌트들을 분리하고 있습니다. 1번의 이유인 "해당 도메인에서만 재사용됨"은 너무 명확하기 때문에 따로 storybook을 만드는게 맞다고 보지만 위에서 언급한 LoginPage에 LoginInpput, PasswordInput을 담은 form은 그저 UI를 배치하는 방식이며 form안에서 validation을 진행하지 않고, LoginPage의 목적인 "사용자의 이메일, 패스워드를 입력받아 로그인을 진행한다"에 부합하기때문에 굳이 분리시키지 않았습니다.
> 물론 이러한 기준은 사람들마다 의견이 다를수 있을것같습니다. 그래서 차라리 storybook을 만들어야하는 컴포넌트를 집어주신다면 제가 작업을 할수 있을것 같습니다.
> 
> (그리고 이걸 간단하게 요약하면 UI를 구현하는 코드가 많다면(관심사의 분리) `_component`에 구현한다고 생각할수있습니다)

* `"해당 도메인에서 재사용되는가?"`: 이 내용대로라면 단 한번만 사용되는 코드는 무조건 분리를 안한다는 건가요? 코드를 분리하는 이유는 재사용을 위한것도 있지만 복잡도를 낮추고 유지보수하기 편하게 만들기 위한 것이 더 큽니다. 이미 위에사례가 있네요.
>> 실제 KiwiBackground.tsx는 별 코드가 없고, 흐름상 크게 문제가 없는것 같지만, KiwiBackground.css.ts에 디자인을 구현하기 위한 많은 코드가 있기때문에 분리하였습니다

* `해당 도메인의 page.tsx 흐름에 벗어나는 컴포넌트인가?`:  `page.tsx`에서는 해당 페이지의 로직을 구현합니다. 그 외의 모든 요소는 유저에게 입력을 받고 출력하기 위해 필요한 것이지, 그 요소가 어떻게 생겼고는 중요하지 않습니다. 예를 들어보겠습니다. 로그인 페이지의 경우에는 계정 정보를 입력받기 위한 폼이 있을텐데 이 폼은 이메일과 비밀번호를 입력받기 위해 필요한 것이지, 페이지 컨트롤 플로우와는 전혀 관계가 없습니다. 해당 폼을 다른 폼으로 바꿔서 입력을 받으면 페이지 코드 흐름이 불가능해지나요? 마찬가지로 대부분의 요소들은 페이지 코드 흐름에 별 관계가 없습니다. 이미 위에서도 언급하셨네요.
>> 위에서 언급한 LoginPage에 LoginInpput, PasswordInput을 담은 form은 그저 UI를 배치하는 방식이며 form안에서 validation을 진행하지 않고...

2023-10-20 12:47 UTC, nnnlog requested changes

2023-10-20 12:47 UTC, nnnlog commented on frontend/src/pages/login/device-register/page.tsx
> +      <Show when={passcodeResponse.state !== 'unresolved'}>
Form으로 감싸서 Input에서 Enter 등의 방법으로 Submit 되도록 해주면 좋을 것 같습니다.

2023-10-20 12:54 UTC, Su-Yong commented
> "해당 도메인에서 재사용되는가?": 이 내용대로라면 단 한번만 사용되는 코드는 무조건 분리를 안한다는 건가요? 코드를 분리하는 이유는 재사용을 위한것도 있지만 복잡도를 낮추고 유지보수하기 편하게 만들기 위한 것이 더 큽니다. 이미 위에사례가 있네요.

이부분은 저도 동의합니다. "코드 분리는 복잡도를 낮추고 유지보수하기 편하게 해야한다"의 대응하는것이 "page.tsx의 흐름에 맞지 않는 컴포넌트이냐"입니다. 제가 좀 설명을 잘 못한거 같아서 아쉽네요.

  > 해당 도메인의 page.tsx 흐름에 벗어나는 컴포넌트인가?: page.tsx에서는 해당 페이지의 로직을 구현합니다. 그 외의 모든 요소는 유저에게 입력을 받고 출력하기 위해 필요한 것이지, 그 요소가 어떻게 생겼고는 중요하지 않습니다. 예를 들어보겠습니다. 로그인 페이지의 경우에는 계정 정보를 입력받기 위한 폼이 있을텐데 이 폼은 이메일과 비밀번호를 입력받기 위해 필요한 것이지, 페이지 컨트롤 플로우와는 전혀 관계가 없습니다. 해당 폼을 다른 폼으로 바꿔서 입력을 받으면 페이지 코드 흐름이 불가능해지나요? 마찬가지로 대부분의 요소들은 페이지 코드 흐름에 별 관계가 없습니다. 이미 위에서도 언급하셨네요.

맞습니다 요소의 생김새는 전혀 중요하지 않습니다. 대부분의 요소가 페이지 코드 흐름과 관련 없다는것도 동의합니다. 그래서 저는 "LoginForm(위에서말한 email, password 인풋받는 form 이하생략하겠습니다)과 같이 바로 input값을 꺼내고 click이벤트를 받는 요소들을 굳이 분리시켜야 하는가"에 대한 질문에 NO라고 답을 한것입니다. 파일을 분리해서 코드 복잡도를 낮추고 유지보수하는것이 좋지만, 너무 많이 분리해버리면 코드를 보기 어려운경우가 생겼습니다. "LoginForm"의 경우 어떻게 구현되어있는지 알기위해 다른 파일로 이동하여 확인하는것은 불필요한 절차라고 생각했고, storybook으로 만드는것도 재사용가능한 요소들의 집합으로만 구성되어있기 때문에 필요없다라고 판단하였습니다.

지금 글을 적으면서 느낀게, LoginForm과 같은경우는 추후에 CheckBox도 들어오니 분리할 이유가 있다고 생각합니다.
![image](https://github.com/KiwiTalk/KiwiTalk/assets/13764936/d5d463fc-a0e1-4d61-9201-e5abee7c692f)
이런 부분까지는 굳이 storybook을 안쓰는게 낫다고 생각합니다

2023-10-20 13:09 UTC, Su-Yong commented
> ...
> 하지만 이런 부분까지는 굳이 storybook을 안쓰는게 낫다고 생각합니다

일단 현재 수정중인부분
- [ ] LoginForm
- [ ] LoginInfoPanel
- [ ] PasscodeForm
- [ ] DeviceRegisterForm

이렇게 분리하고 있습니다. 혹시 추가로 더 코드 split해야할부분 있는거 같으시면 댓글 달아주세용

2023-10-20 17:24 UTC, Su-Yong commented
> > ...
> > 하지만 이런 부분까지는 굳이 storybook을 안쓰는게 낫다고 생각합니다
> 
> 일단 현재 수정중인부분
> 
> * [ ]  LoginForm
> * [x]  LoginStepper
> * [x]  PasscodeForm
> * [ ]  DeviceRegisterForm
> 
> 이렇게 분리하고 있습니다. 혹시 추가로 더 코드 split해야할부분 있는거 같으시면 댓글 달아주세용

![image](https://github.com/KiwiTalk/KiwiTalk/assets/13764936/e5b86a65-a35b-4519-871e-948683145d2e)
![image](https://github.com/KiwiTalk/KiwiTalk/assets/13764936/8088ab3f-85df-4d93-9985-294c3a7d7f6b)

이 두부분이 LoginForm, DeviceRegisterForm인데 따로 컴포넌트 빼기에는 너무 작은양이라 냅뒀습니다 (ref대신 formData이용하도록 바꿨습니다)

2023-10-21 03:02 UTC, nnnlog approved these changes

2023-10-21 08:50 UTC, storycraft approved these changes

2023-10-21 12:24 UTC, JellyBrick approved these changes

2023-10-21 12:43 UTC, HelloWorld017 commented on frontend/src/features/theme/vars.css.ts
> +    surfacePrimary: {
surface 보다는 glass와 구별되는 다른 이름이 더 좋을 것 같아요 `solidPrimary` ..? `mattePrimary` ..?

2023-10-21 12:43 UTC, HelloWorld017 commented on frontend/src/features/theme/vars.css.ts
> +    glassSecondary: {
`secondary` 가 `primary` 보다 위계 상 더 위일 것 같아요! 서로 이름 바꾸면 좋을 것 같습니당

2023-10-21 12:43 UTC, HelloWorld017 commented on frontend/src/pages/_components/window-controls/window-controls.css.ts
> +  'zIndex': 99999999,
zIndex enum을 하나 만들어서 Tooltip: 1000, Modal: 2000, ..., WindowFrame: 10000 이런 식으로 zIndex를 명시적으로 관리하면 좋을 것 같아요. 이거 항상 파워인플레가 일어났던 거 같아서...

2023-10-21 12:46 UTC, JellyBrick commented on frontend/src/pages/_components/window-controls/window-controls.css.ts
> +  'zIndex': 99999999,
찬성합니다

2023-10-22 00:55 UTC, Su-Yong commented
PR이 너무 비대해져서 @HelloWorld017 님의 리뷰내용은 다른 PR로 분리하겠습니다

2023-10-22 02:24 UTC, merged