[WIP] 채팅 페이지
KiwiTalk/KiwiTalk pull request #2109
Opened 2023-10-25 18:30 UTC by Su-Yong

## Description
![image](https://github.com/KiwiTalk/KiwiTalk/assets/13764936/c67fa5c4-fc83-4145-a2de-20edce57f68b)

- 채팅 페이지를 구현합니다

## Changelog
- add `Message`
- add `MessageList`
- add `MessageInput`
- add `VirtualList` (WIP) (사용하기 좋은 라이브러리가 있을 시 변경예정) (후보군 `@tanstack/virtual`, `solid-virtual-container`)
- add `ChannelHeader`

## Migration

2023-10-26 16:07 UTC, Su-Yong commented
리뷰 때 부탁 드릴 것이 총 3가지 있습니다.

1. 현재 코드 복잡도가 꽤나 높은 것으로 보이니, 최대한 코드 복잡도를 낮출 수 있는 방안으로 리뷰를 부탁 드립니다
2. `MessageList`의 기본 `ViewModel`을 외부에서 구현하였습니다. `ChatPage`에서 동일한 데이터를 함께 다루기 위함인데, 더 좋은 방법이 있는지 확인 부탁드립니다.
3. 마지막으로 `VirtualList`는 직접 구현하는 구현체 말고, `@tanstack/solid-virtual`이나, `solid-virtual-container`와 같은 외부 라이브러리들로 대체가능하다면, 가능한 라이브러리를 알려주시면 감사하겠습니다 (예시로 든 두 라이브러리는 각각 모종의 이유로 사용하지 않습니다. 사유는 위에 적혀있습니다)

2023-10-27 06:42 UTC, storycraft requested changes
일단 코드를 시간을 들여서 다듬을 필요가 있어보입니다. 그리고 코드중에서 크게 바꿔야 할 점이 몇가지 보였는데

1. ViewModelType으로 끝나는 타입들: 따로 분리한 이유를 모르겠습니다. 내부 타입으로 Accessor를 쓰는 이유도 잘 모르겠네요. 써서 얻는 이점도 없고 관리하기 힘듭니다. (+ 불필요한 untrack 사용 필요)
2. 복잡한 타입: 몇몇 코드에서 타입 가지고 이리저리 하는게 보이는데 굉장히 특별한 경우가 아니면 사실 별로 보기 안 좋고 쓰기도 안좋습니다. 오히려 이런 타입들 때문에 코드가 불필요하게 복잡해집니다. (`frontend/src/api/client/channel.ts` 리뷰 참고)
3. 과다한 `createMemo` 사용: 대부분의 코드에서 `createMemo`는 쓸일이 거의 없습니다.  쓰이는 경우 대부분 불필요하거나, 잘못 작성된 코드일 가능성이 높습니다.

고칠 때 위 세가지를 참고하셔서 고치면 좋겠네요.

추가적으로 가상 스크롤의 경우 목적에 맞게 보이지 않는 요소의 경우 DOM 트리에서 삭제 해주는 기능도 있었으면 좋겠습니다.

2023-10-27 06:42 UTC, storycraft commented on frontend/src/api/client/channel.ts
BigInt로 바꿔서 반환하지 말고 필요한곳에서 BigInt로 바꿔서 써주세요. (`logId` 처럼)

2023-10-27 06:42 UTC, storycraft commented on frontend/src/pages/main/_utils/index.ts
훅들은 `_utils`이 아닌 다른 폴더에 배치 하는게 좋지 않을까요? 그리고 되도록이면 utils 같은 폴더 이름은 안 써주셨으면 합니다.

2023-10-27 06:42 UTC, storycraft commented on frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
> +  let loadCooldown: NodeJS.Timeout | null = null;
number 타입을 사용해주세요

2023-10-27 06:42 UTC, storycraft commented on frontend/src/pages/main/channel/chat/page.tsx
> +    if (!isLoad) return;
위 if 문에 합쳐도 되지 않을까요?

2023-10-27 06:42 UTC, storycraft commented on frontend/src/pages/main/channel/chat/page.tsx
> +    if (!id) return null;
여기도 두 if문을 하나로 합치는게 더 좋아보이네요

2023-10-27 07:02 UTC, Su-Yong commented on frontend/src/pages/main/_utils/index.ts
이부분은 프론트엔드구조 재정립 issue에 나와있는 부분입니다 따로 훅을 빼야한다면 features/hooks로 빼는게 좋다 생각하네요

features/hook에다 훅을 모두 구현하는게 나을까요?

2023-10-27 07:16 UTC, Su-Yong commented
> 일단 코드를 시간을 들여서 다듬을 필요가 있어보입니다. 그리고 코드중에서 크게 바꿔야 할 점이 몇가지 보였는데
> 
> 
> 
> 1. ViewModelType으로 끝나는 타입들: 따로 분리한 이유를 모르겠습니다. 내부 타입으로 Accessor를 쓰는 이유도 잘 모르겠네요. 써서 얻는 이점도 없고 관리하기 힘듭니다. (+ 불필요한 untrack 사용 필요)
> 
> 2. 복잡한 타입: 몇몇 코드에서 타입 가지고 이리저리 하는게 보이는데 굉장히 특별한 경우가 아니면 사실 별로 보기 안 좋고 쓰기도 안좋습니다. 오히려 이런 타입들 때문에 코드가 불필요하게 복잡해집니다. (`frontend/src/api/client/channel.ts` 리뷰 참고)
> 
> 3. 과다한 `createMemo` 사용: 대부분의 코드에서 `createMemo`는 쓸일이 거의 없습니다.  쓰이는 경우 대부분 불필요하거나, 잘못 작성된 코드일 가능성이 높습니다.
> 
> 
> 
> 고칠 때 위 세가지를 참고하셔서 고치면 좋겠네요.
> 
> 
> 
> 추가적으로 가상 스크롤의 경우 목적에 맞게 보이지 않는 요소의 경우 DOM 트리에서 삭제 해주는 기능도 있었으면 좋겠습니다.
> 
> 

혹시 2번에서 언급한 리뷰가 안보이는데 어떤내용인지 알수있을까요?

2023-10-27 07:18 UTC, storycraft commented on frontend/src/pages/main/_utils/index.ts
아니요. 같은 폴더에 이름만 그냥 `_hooks`로 바꾸는게 좋을 것 같네요

2023-10-27 07:19 UTC, storycraft requested changes

2023-10-27 07:19 UTC, storycraft commented on frontend/src/api/client/channel.ts
BigInt로 바꿔서 반환하지 말고 필요한곳에서 BigInt로 바꿔서 써주세요. (logId 처럼)

2023-10-27 07:29 UTC, storycraft commented
> 
> 혹시 2번에서 언급한 리뷰가 안보이는데 어떤내용인지 알수있을까요?

리뷰 업데이트 했습니다

2023-10-27 07:31 UTC, storycraft commented
추가적으로 채팅방을 선택하지 않았을때 채팅창이 보이면 안되고, 채팅 입력창 밑으로 채팅이 보이면 안됩니다. 이 부분도 수정이 필요하네요.

2023-10-28 04:09 UTC, Su-Yong commented on frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
> +  let loadCooldown: NodeJS.Timeout | null = null;
<img width="646" alt="image" src="https://github.com/KiwiTalk/KiwiTalk/assets/13764936/2bb484f8-47d1-4f03-b51d-15b32e27ec3c">

실제타입은 numbe가 맞지만, number를쓰면 타입 오류가 발생합니다

2023-10-28 04:25 UTC, Su-Yong commented
> 일단 코드를 시간을 들여서 다듬을 필요가 있어보입니다. 그리고 코드중에서 크게 바꿔야 할 점이 몇가지 보였는데
> 
> 1. ViewModelType으로 끝나는 타입들: 따로 분리한 이유를 모르겠습니다. 내부 타입으로 Accessor를 쓰는 이유도 잘 모르겠네요. 써서 얻는 이점도 없고 관리하기 힘듭니다. (+ 불필요한 untrack 사용 필요)
> 2. 복잡한 타입: 몇몇 코드에서 타입 가지고 이리저리 하는게 보이는데 굉장히 특별한 경우가 아니면 사실 별로 보기 안 좋고 쓰기도 안좋습니다. 오히려 이런 타입들 때문에 코드가 불필요하게 복잡해집니다. (`frontend/src/api/client/channel.ts` 리뷰 참고)
> 3. 과다한 `createMemo` 사용: 대부분의 코드에서 `createMemo`는 쓸일이 거의 없습니다.  쓰이는 경우 대부분 불필요하거나, 잘못 작성된 코드일 가능성이 높습니다.
> 
> 고칠 때 위 세가지를 참고하셔서 고치면 좋겠네요.
> 
> 추가적으로 가상 스크롤의 경우 목적에 맞게 보이지 않는 요소의 경우 DOM 트리에서 삭제 해주는 기능도 있었으면 좋겠습니다.

1. 1번내용은 반영하도록 하겠습니다
2. 2번은 resolve했습니다
3. 3번의 내용은 확인해본 결과, `VirtualList`와 `MessageList`에서 사용한걸로 보이는데, 이부분에 사용된 createMemo는 필요하기때문에 쓰였습니다. `instance.users()`는 `VirtualList` 특성상, 굉장히 자주 읽게 됩니다 따라서 이부분은 메모를 하는게 성능상 이득이 있습니다. 그외 나머지 부분은 다시 확인후에 없에고 필요한부분은 주석을 달아두도록 하겠습니다

그리고 가상 스크롤의 경우 보이지 않는 요소는 solid에 의해 자동 소거됩니다 개발자 도구를 켜고 보면 일정 갯수의 element만 유지되는것을 볼 수 있습니다. 실제로 사용했을때는 보이지 않는 위치에 있는 element도 랜더링 되는것을 볼 수 있는데, 이는 `VirtualList`에 있는 `overscan` 값 때문입니다. `overscan`값을 0으로 만들면 정말 보이는 부분만 렌더링을 진행하고, `overscan`의 수치만큼 위아래로 추가로 렌더링을 합니다. 굉장히 빠르게 스크롤을 할 경우 `overscan`값이 0이면 엘리먼트가 중간중간 보이지 않는 문제가 발생할수 있어 5정도로 수치를 정했습니다

2023-10-28 10:01 UTC, storycraft requested changes

2023-10-28 10:01 UTC, storycraft commented on frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
> +const isDiff = (a: number, b: number) => {
이 경우 각 인자가 초 단위의 시간 이므로 `Math.abs(a - b) < 60` 으로 해도 될 것 같네요.

2023-10-28 10:13 UTC, Su-Yong commented on frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
> +const isDiff = (a: number, b: number) => {
그경우 이 동작과 살짝 다른게, 11분 59초와 12분 01초의 시간을 비교하면  Math.abs(a - b)는 3000ms가 나오지만, 실제론 보여야하기때문에 year, month, date, hours, minutes를 각각 다 비교해서 다른지 하였습니다

2023-10-29 13:52 UTC, storycraft approved these changes
일단 더이상 레이아웃이 깨지는 문제는 없으니 마지하겠습니다. 다만 코드부분에 대해선 지속적으로 리펙터링등을 통해 구조 개선이 이뤄져야 할것 같네요.

2023-10-29 13:52 UTC, storycraft commented on frontend/src/api/client/channel.ts
>  import { tauri } from '@tauri-apps/api';
bigint로 변환될수 있는 64비트 정수의 경우 타입을 사용해서 나중에 구분할수 있도록 하겠습니다.

2023-10-29 13:52 UTC, storycraft commented on frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
> +const isDiff = (a: number, b: number) => {
아 제가 코드를 잘못 작성했네요. `Math.floor(a / 60) - Math.floor(b / 60) !== 0`으로 고치겠습니다.

2023-10-29 13:53 UTC, merged